name: Push to master

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/setup-node@v2'
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args:
            'deploy'

