name: Push to master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: Production

    steps:
      - name: Setup
        run: curl -L https://fly.io/install.sh | sh
        
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - uses: 'actions/setup-node@v2'
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
        
      - name: Test
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: echo "heyy" && echo $FLY_API_TOKEN

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: deploy .
